image:
  repository: artifactory.dagility.com/docker/phoenix-feb13-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: phoenix-feb13-frontend-habitat-test3.dagility.com
    paths:
    - /
serviceAccount:
  create: false
